name: Tax-Forecaster CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'
          cache: 'maven'

      - name: Build and Test
        run: mvn clean install -DskipTests=false

  docker-build-push:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: SobhanDev
          password: sobhan8181

      - name: Build and Push Docker Image
        run: |
          docker build -t my-docker-repo/my-app:latest .
          docker push my-docker-repo/my-app:latest
